### PR TITLE
feature/INTERLOK-2758 - statement parameters should be built automatically

### PR DESCRIPTION
**Pull request by albinoloverats**
## Motivation

To make statement-parameters redundant we need a new syntax:

```sql
INSERT INTO hits (reference, message_id, id, entity_id, blocking) VALUES (%sql_metadata{string:reference, %sql_metadata{string:%uniqueId}, %sql_metadata{string:id}, %sql_metadata{string:entity_id}, %s
```

Where under the covers we actually turn that into "INSERT INTO hits (reference, message_id, id, entity_id, blocking) VALUES (?, ?, ? ,? ,?);" and then generate a list of statement parameters automatically:

```xml
<jdbc-string-statement-parameter>
    <query-string>reference</query-string>
    <query-type>metadata</query-type>
  </jdbc-string-statement-parameter>
  <jdbc-string-statement-parameter>
    <query-string>message_id</query-string>
    <query-type>id</query-type>
  </jdbc-string-statement-parameter>
  <jdbc-string-statement-parameter>
    <query-string>id</query-string>
    <query-type>metadata</query-type>
  </jdbc-string-statement-parameter>
  <jdbc-string-statement-parameter>
    <query-string>entity_id</query-string>
    <query-type>metadata</query-type>
  </jdbc-string-statement-parameter>
  <jdbc-string-statement-parameter>
    <query-string>blocking</query-string>
    <query-type>metadata</query-type>
  </jdbc-string-statement-parameter>
  <statement>INSERT INTO hits (reference, message_id, id, entity_id, blocking) VALUES (?, ?, ? ,? ,?);</statement>
```

## Modification

In addition to all of the *default* gradle files, there is a new service `JDBCStatementBuilderService` and accompanying test.

## PR Checklist

- [x] been self-reviewed.
- [x] Added javadocs for most classes and all non-trivial methods
- [x] Added supporting annotations (like XStreamAlias / ComponentProfile)
- [x] Checked that new 3rd party dependencies are appropriately licensed
- [x] Added comments explaining the "why" and the intent of the code wherever it would not be obvious for an unfamiliar reader
- [x] Added unit tests or modified existing tests to cover new code paths
- [x] Tested new/updated components in the UI
- [x] Checked the display of the component in the UI

## Result

It should be easier to configure a JDBC capture/query statement.

## Testing

Unit tests cover all of the code. Attached is a [config](https://github.com/adaptris/interlok-ds/files/6472997/adapter.xml.txt) that will read a file from the file system and put it into an in-memory derby database before retrieving it. Both of these actions use the new statement builder services.

### CODE REVIEW

**Comment by quotidian-ennui** [comment]
- You can get rid of the circleci + travis configuration since we don't use em.
- .lgtm.yml should pin the correct gradle version

**Comment by quotidian-ennui** [comment]
@albinoloverats we need to change things up so that we're using "GITHUB NATIVE" dependabot


- you need to git mv .dependabot/config.yml -> .github/dependabot.yml 

dependabot.yml should contain something like:  reference is : https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

```
version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/interlok
    username: dummy
    password: dummy-since-this-is-a-public-repo

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - quotidian-ennui
      - mcwarman
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella
```

**Comment by quotidian-ennui** [comment]
- JdbcStatementQueryBuilder doesn't allow you to "choose the output style" : nothing shows up as a configurable component c.f. ResultSetTranslator in jdbc-data-query-service
So I can do this : (this is working off the liverpool_transfers database created as part of the interlok tests).

```xml
<jdbc-data-query-statement-builder-service>
  <unique-id>select </unique-id>
  <connection class="shared-connection">
    <lookup-name>shared-mysql</lookup-name>
  </connection>
  <statement>SELECT * from liverpool_transfers where club = %sql_metadata{string:club}</statement>
</jdbc-data-query-statement-builder-service>
```

Which gives me XML output; but I want to be able to do this.
```xml
<jdbc-data-query-statement-builder-service>
  <unique-id>select </unique-id>
  <connection class="shared-connection">
    <lookup-name>shared-mysql</lookup-name>
  </connection>
  <statement>SELECT * from liverpool_transfers where club = %sql_metadata{string:club}</statement>
  <result-set-translator class="jdbc-json-first-resultset-output">
    <column-name-style>NoStyle</column-name-style>
  </result-set-translator>
</jdbc-data-query-statement-builder-service>
```

so that I get JSON immediately.

**Comment by quotidian-ennui** [comment]
- jdbc-data-capture-statement-builder doesn't appear to work at-all
(again working off the liverpool_transfers database).

```xml
              <jdbc-data-capture-statement-builder-service>
                <unique-id>jdbc-insert</unique-id>
                <connection class="shared-connection">
                  <lookup-name>shared-mysql</lookup-name>
                </connection>
                <statement>INSERT INTO liverpool_transfers (type, player, club, amount, manager, date) VALUES (%sql_metadata{string:action}, %sql_metadata{string:name}, %sql_metadata{string:club}, %sql_metadata{integer:value},
%sql_metadata{string:manager}, NOW())</statement>
              </jdbc-data-capture-statement-builder-service>
```

If we add logging into the "prepare" statement of JdbcStatementBuilderService 
```
  @Override
  public void prepareService() throws CoreException
  {
    JdbcServiceWithParameters service = buildService(statement);
    log.trace("Wrapped Service : {}", DefaultMarshaller.getDefaultMarshaller().marshal(service));
    LifecycleHelper.prepare(service);
  }
```

We see this output : 
```
TRACE [pool-9-thread-1] [c.a.i.j.JDBCDataCaptureStatementBuilderService.prepareService()] [{}] Wrapped Service : <jdbc-data-capture-service>
  <unique-id>cbceeb6d-31e1-456a-b466-a256bd9a36fa</unique-id>
  <connection class="shared-connection">
    <lookup-name>shared-mysql</lookup-name>
  </connection>
  <parameter-applicator class="named-parameter-applicator">
    <parameter-name-prefix>#</parameter-name-prefix>
    <parameter-name-regex>#\w*</parameter-name-regex>
  </parameter-applicator>
  <statement>INSERT INTO liverpool_transfers (type, player, club, amount, manager, date) VALUES (%sql_metadata{string:action}, %sql_metadata{string:name}, %sql_metadata{string:club}, %sql_metadata{integer:value},
%sql_metadata{string:manager}, NOW())</statement>
</jdbc-data-capture-service>
```

Which means that building the statement has failed, but it's difficult to see where...

**Comment by quotidian-ennui** [comment]
Also, jdbc-data-query-statement-builder should probably extend Jdbc-raw-data-capture since won't be interrogating the payload (so we don't need all the iterating behaviours anyway).

**Comment by sebastien-belin-adp** [comment]
@albinoloverats if you look at the statement in Lewin's config:

```
  <statement>INSERT INTO liverpool_transfers (type, player, club, amount, manager, date) VALUES (%sql_metadata{string:action}, %sql_metadata{string:name}, %sql_metadata{string:club}, %sql_metadata{integer:value},
%sql_metadata{string:manager}, NOW())</statement>
```

`%sql_metadata{string:manager}, NOW())` is on a new line, there is an end of line char on the line above.
The regex doesn't handle that (does it need to?) and that's probably why Lewin's config is not working but you may struggle to reproduce it.

**Comment by aaron-mcgrath-adp** [comment]
I tested against a MySQL database I have running and it seems to work quite nicely.
Seems like a decent implementation.

We are def gonna need some javadoc/documentation around the new %sql_ language you've created.  Like what datatypes are available etc.

Looks good though.

**Review by aaron-mcgrath-adp — APPROVED** [review]
Needs javadoc/documentation, but works nicely.

**Comment by albinoloverats** [comment]
> documentation around the new %sql_ language

Ah yes, of course.

**Pull request merged**
